# TCL File Generated by Component Editor 20.1
# Sun Nov 12 10:28:31 JST 2023
# DO NOT MODIFY


#
# WLAN11a_RX "WLAN11a_RX" v1.0
#  2023.11.12.10:28:31
#
#

#
# request TCL package from ACDS 16.1
#
package require -exact qsys 16.1


#
# module WLAN11a_RX
#
set_module_property DESCRIPTION ""
set_module_property NAME WLAN11a_RX
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME WLAN11a_RX
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


#
# file sets
#
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL WLAN11a_RX_top
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file ABdhOeLDORVn0vZaooeJBC.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/ABdhOeLDORVn0vZaooeJBC.v
add_fileset_file ALNDhctqT9eEUG85mwh7IF.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/ALNDhctqT9eEUG85mwh7IF.v
add_fileset_file AUA9ImjY6Um40l55rOH1PF.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/AUA9ImjY6Um40l55rOH1PF.v
add_fileset_file AdeE9EpFEfxEt3qiW4IBgF.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/AdeE9EpFEfxEt3qiW4IBgF.v
add_fileset_file AtKbzUc0pFhW0Fg6g62RG.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/AtKbzUc0pFhW0Fg6g62RG.v
add_fileset_file B02fWUreKJeb07GGzGDTfC.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/B02fWUreKJeb07GGzGDTfC.v
add_fileset_file CM6pKLnPa8TQS2oDurfatC.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/CM6pKLnPa8TQS2oDurfatC.v
add_fileset_file CnYcggHfLoyMVWpPmuWINC.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/CnYcggHfLoyMVWpPmuWINC.v
add_fileset_file DRDllfBfmv1rjrQnl3BkpF.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/DRDllfBfmv1rjrQnl3BkpF.v
add_fileset_file Ddohena1Y3ujaGj9ngMoHF.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/Ddohena1Y3ujaGj9ngMoHF.v
add_fileset_file DrztAm9aEseYxhXY7dT0N.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/DrztAm9aEseYxhXY7dT0N.v
add_fileset_file EPWxgVvVnCcwGq8sQkKygG.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/EPWxgVvVnCcwGq8sQkKygG.v
add_fileset_file ESq8DYoI7ubF3ByYPGq9FD.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/ESq8DYoI7ubF3ByYPGq9FD.v
add_fileset_file EaJeUccSkz0WsUUR1AJjNE.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/EaJeUccSkz0WsUUR1AJjNE.v
add_fileset_file F0EOxpEVDpGvDPEHWlMUdB.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/F0EOxpEVDpGvDPEHWlMUdB.v
add_fileset_file Ffs8rfQI9SxEu5t5VXuA9.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/Ffs8rfQI9SxEu5t5VXuA9.v
add_fileset_file HAxahfAQaz4fwpYGwAJLF.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/HAxahfAQaz4fwpYGwAJLF.v
add_fileset_file HBWFh4Hvs8aQZOr7kf1M4F.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/HBWFh4Hvs8aQZOr7kf1M4F.v
add_fileset_file I4NrCsM46z8lM4AKxFof9D.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/I4NrCsM46z8lM4AKxFof9D.v
add_fileset_file Iw5mqWj2FSR933NDYVXtW.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/Iw5mqWj2FSR933NDYVXtW.v
add_fileset_file J2fQniLbxip6pBKeCsfSnF.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/J2fQniLbxip6pBKeCsfSnF.v
add_fileset_file KcqcTSWsbDihSN77Gh81MC.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/KcqcTSWsbDihSN77Gh81MC.v
add_fileset_file Kz0W2qfMbSJlBM1FZ20GbC.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/Kz0W2qfMbSJlBM1FZ20GbC.v
add_fileset_file LVdKs9rIIaCVABzENlmDOB.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/LVdKs9rIIaCVABzENlmDOB.v
add_fileset_file LnV5jlPlaiEpOIsOFXYBH.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/LnV5jlPlaiEpOIsOFXYBH.v
add_fileset_file NLZIZm1MSkFbUmBqJQPh5F.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/NLZIZm1MSkFbUmBqJQPh5F.v
add_fileset_file NuWoNRQ4SNBL01N6vRfXhH.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/NuWoNRQ4SNBL01N6vRfXhH.v
add_fileset_file OWNEfvo3AQ9D11d0f86PHD.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/OWNEfvo3AQ9D11d0f86PHD.v
add_fileset_file OiKdgWYIZlOwGvPeczcWMF.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/OiKdgWYIZlOwGvPeczcWMF.v
add_fileset_file OyQ2XmipFvJR47cPUnD7aC.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/OyQ2XmipFvJR47cPUnD7aC.v
add_fileset_file PamPkDyckFC5Zfey81GmBF.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/PamPkDyckFC5Zfey81GmBF.v
add_fileset_file QamMe8RZKVl3rXCbMHDCDC.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/QamMe8RZKVl3rXCbMHDCDC.v
add_fileset_file R8fau3wXklpO2Lole2kRHB.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/R8fau3wXklpO2Lole2kRHB.v
add_fileset_file RFCE8jqCbQGU8r6uHCVoBD.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/RFCE8jqCbQGU8r6uHCVoBD.v
add_fileset_file Re43L0onx08rEigFnWtcVH.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/Re43L0onx08rEigFnWtcVH.v
add_fileset_file SgasueeUyuMIJse8biKB9.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/SgasueeUyuMIJse8biKB9.v
add_fileset_file TIV7usdcMJnRrn4qjLCtGB.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/TIV7usdcMJnRrn4qjLCtGB.v
add_fileset_file TOkUMTJrlyeClvvhbiWTQD.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/TOkUMTJrlyeClvvhbiWTQD.v
add_fileset_file Toakj5KycMxajHCbPUfMWF.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/Toakj5KycMxajHCbPUfMWF.v
add_fileset_file UQ61U5eUUqW8tXrNoX7eqE.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/UQ61U5eUUqW8tXrNoX7eqE.v
add_fileset_file Uprz1EsA99BqLL7PlVMHMH.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/Uprz1EsA99BqLL7PlVMHMH.v
add_fileset_file VHQqRbdYqJW1ageEhWczBH.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/VHQqRbdYqJW1ageEhWczBH.v
add_fileset_file WLAN11a_RX_RxPHY_RxPHY.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/WLAN11a_RX_RxPHY_RxPHY.v
add_fileset_file XbE49a2V4inPzalvASjFkF.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/XbE49a2V4inPzalvASjFkF.v
add_fileset_file YdlXrT440113T9kOa4cU9G.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/YdlXrT440113T9kOa4cU9G.v
add_fileset_file Z8dIcpYMzZXxJuXeHhgAnF.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/Z8dIcpYMzZXxJuXeHhgAnF.v
add_fileset_file a2vV879oHmBXiGiGe7GrG7F.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/a2vV879oHmBXiGiGe7GrG7F.v
add_fileset_file a6JJxmCJdcCBHPaIBQBhjiC.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/a6JJxmCJdcCBHPaIBQBhjiC.v
add_fileset_file aHrmTdZwMKECvkJwXz5gY.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/aHrmTdZwMKECvkJwXz5gY.v
add_fileset_file aJV4SvNOF6dVTL6PIdwWTG.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/aJV4SvNOF6dVTL6PIdwWTG.v
add_fileset_file aUv69oLOwKzssAc1tFBwyB.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/aUv69oLOwKzssAc1tFBwyB.v
add_fileset_file aVhq1ck0t6hzMXZClZrneG.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/aVhq1ck0t6hzMXZClZrneG.v
add_fileset_file b7aLdmsiGVro6DfZPIdaeD.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/b7aLdmsiGVro6DfZPIdaeD.v
add_fileset_file b8Yh798vvlhqyDJTzaWE1G.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/b8Yh798vvlhqyDJTzaWE1G.v
add_fileset_file b9LcOxoiCPWF0yzox12qiPC.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/b9LcOxoiCPWF0yzox12qiPC.v
add_fileset_file bz3xDtfi24AFWMZXroAV4F.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/bz3xDtfi24AFWMZXroAV4F.v
add_fileset_file c6NvMEO2i27wn9vIrWZHj5E.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/c6NvMEO2i27wn9vIrWZHj5E.v
add_fileset_file cch63H8dXQyNVlDKmIMlJD.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/cch63H8dXQyNVlDKmIMlJD.v
add_fileset_file cfwXsaVCcheBwaSpqF76IF.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/cfwXsaVCcheBwaSpqF76IF.v
add_fileset_file chHYQLOGbHN5s8mXbw0isE.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/chHYQLOGbHN5s8mXbw0isE.v
add_fileset_file d3NTiMHcdqqbz2uk7X7cRvG.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/d3NTiMHcdqqbz2uk7X7cRvG.v
add_fileset_file d4RJvBBCsOsrOfLKbyW9QIH.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/d4RJvBBCsOsrOfLKbyW9QIH.v
add_fileset_file d64paltqAmmPqdPO6rSRLPC.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/d64paltqAmmPqdPO6rSRLPC.v
add_fileset_file dvmhNVL3PvAjQLpKfEGapB.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/dvmhNVL3PvAjQLpKfEGapB.v
add_fileset_file eTNXX2HlzXLcHK9W4dmdmD.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/eTNXX2HlzXLcHK9W4dmdmD.v
add_fileset_file elwLY59YH4UecJ1er8HUr.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/elwLY59YH4UecJ1er8HUr.v
add_fileset_file etpWoEgI6QflkuvLegE1jD.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/etpWoEgI6QflkuvLegE1jD.v
add_fileset_file evr0qqTKrwfqLQHpC6b7yC.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/evr0qqTKrwfqLQHpC6b7yC.v
add_fileset_file f6Rd1qFNUtPNxZGbPtlkr7.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/f6Rd1qFNUtPNxZGbPtlkr7.v
add_fileset_file f8OenWtmP7HYLjOff9epw.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/f8OenWtmP7HYLjOff9epw.v
add_fileset_file gyZKZhAj0ZZBUfxNicjt3D.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/gyZKZhAj0ZZBUfxNicjt3D.v
add_fileset_file h1MFe6UmIimeps75F63ZtTH.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/h1MFe6UmIimeps75F63ZtTH.v
add_fileset_file h7NwsiySxTNQMJLn7No6IGE.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/h7NwsiySxTNQMJLn7No6IGE.v
add_fileset_file iCBOwreHSCXW2vsJU6MuEG.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/iCBOwreHSCXW2vsJU6MuEG.v
add_fileset_file j6jxOYGbqtyCuAHon0LaDuF.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/j6jxOYGbqtyCuAHon0LaDuF.v
add_fileset_file jN11gThRy1aW8aYnGZNHXB.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/jN11gThRy1aW8aYnGZNHXB.v
add_fileset_file kQCfAfjcOud3KrIc730QTB.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/kQCfAfjcOud3KrIc730QTB.v
add_fileset_file kcPnZ7bRqfuXOAsJoSzzyE.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/kcPnZ7bRqfuXOAsJoSzzyE.v
add_fileset_file kirJfRZliEZC1GSKABhUHC.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/kirJfRZliEZC1GSKABhUHC.v
add_fileset_file knrnNDJXrrORyHzKRHKmvH.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/knrnNDJXrrORyHzKRHKmvH.v
add_fileset_file lJJIyEE1Ki1BbnHVwYHHHH.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/lJJIyEE1Ki1BbnHVwYHHHH.v
add_fileset_file lRmm87Nsz1AsPd3Pd0NMHC.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/lRmm87Nsz1AsPd3Pd0NMHC.v
add_fileset_file lb7Jbfm88jOjQ4O1KPAFoH.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/lb7Jbfm88jOjQ4O1KPAFoH.v
add_fileset_file lip3Xcl6p2uwvbqN0tihtE.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/lip3Xcl6p2uwvbqN0tihtE.v
add_fileset_file lwD5TTAE1lHYfsRYtk5zuE.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/lwD5TTAE1lHYfsRYtk5zuE.v
add_fileset_file m5CpF6MqnOUeZRHODCQ2WC.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/m5CpF6MqnOUeZRHODCQ2WC.v
add_fileset_file mgDFjbw04YLFr87EwLiiVH.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/mgDFjbw04YLFr87EwLiiVH.v
add_fileset_file n2pLmclsH0VNCTK6ewr3nC.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/n2pLmclsH0VNCTK6ewr3nC.v
add_fileset_file n9AxYG7ErLT6MmvMk7GGhIF.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/n9AxYG7ErLT6MmvMk7GGhIF.v
add_fileset_file n9hKsiu9cltCehLPFaMVXD.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/n9hKsiu9cltCehLPFaMVXD.v
add_fileset_file nKPu7bYF1Rr7JdLZWwB24.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/nKPu7bYF1Rr7JdLZWwB24.v
add_fileset_file o3xoFlHq8HgKSgHarZlh6fF.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/o3xoFlHq8HgKSgHarZlh6fF.v
add_fileset_file oHA7CibAl60jrfv2R2fDVF.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/oHA7CibAl60jrfv2R2fDVF.v
add_fileset_file ot2p0jmIozLIzJQ9e0Sg7D.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/ot2p0jmIozLIzJQ9e0Sg7D.v
add_fileset_file p8WsuwFauZG2ydJRITTv8jC.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/p8WsuwFauZG2ydJRITTv8jC.v
add_fileset_file qB2nwgJRwiZZGwejTaz8S.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/qB2nwgJRwiZZGwejTaz8S.v
add_fileset_file qIZ3QunBkk9NotSUMPswXG.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/qIZ3QunBkk9NotSUMPswXG.v
add_fileset_file qJ6nfLmeBuML3JMAFivMo.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/qJ6nfLmeBuML3JMAFivMo.v
add_fileset_file rhPCmTF3EwHqQELcSmQ6OB.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/rhPCmTF3EwHqQELcSmQ6OB.v
add_fileset_file s1MgWNHYxWQuXwyQmrum6WC.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/s1MgWNHYxWQuXwyQmrum6WC.v
add_fileset_file s85W2RmaTtemlUCI1aXbyD.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/s85W2RmaTtemlUCI1aXbyD.v
add_fileset_file sXQC8HIXXTD0SZeuYX4rhF.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/sXQC8HIXXTD0SZeuYX4rhF.v
add_fileset_file t1kkiXg83V9cx2NAilXfJwG.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/t1kkiXg83V9cx2NAilXfJwG.v
add_fileset_file t9QP4zs56djlMgffxyHghRB.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/t9QP4zs56djlMgffxyHghRB.v
add_fileset_file tIrO5g75wuTiCnDKDd1rPB.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/tIrO5g75wuTiCnDKDd1rPB.v
add_fileset_file u1xSuoYyNtwMe8E8q1dXwD.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/u1xSuoYyNtwMe8E8q1dXwD.v
add_fileset_file v1767WBgBisOyzyEOHDTTpH.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/v1767WBgBisOyzyEOHDTTpH.v
add_fileset_file viD8JV6Po9XJ5SPvGnJogE.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/viD8JV6Po9XJ5SPvGnJogE.v
add_fileset_file vwhM5qauNu5cUT8POAap1F.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/vwhM5qauNu5cUT8POAap1F.v
add_fileset_file w2ll8GIIfseVGdnjY55cOaE.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/w2ll8GIIfseVGdnjY55cOaE.v
add_fileset_file wHsxLt3eTD1IrrrVrna3TE.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/wHsxLt3eTD1IrrrVrna3TE.v
add_fileset_file x1ChulAGIdLXoAIPuTGYtBH.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/x1ChulAGIdLXoAIPuTGYtBH.v
add_fileset_file x92mlxvhDSpvxkx4d1u4TRC.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/x92mlxvhDSpvxkx4d1u4TRC.v
add_fileset_file xNwu69p77SYmvjuF3c18rF.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/xNwu69p77SYmvjuF3c18rF.v
add_fileset_file y8KTZlJu33WXLF7mIqCKkEG.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/y8KTZlJu33WXLF7mIqCKkEG.v
add_fileset_file y8koHqSdKio67vvfS3yqGLE.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/y8koHqSdKio67vvfS3yqGLE.v
add_fileset_file yX8CAnSoop4kWieyoYIzhE.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/yX8CAnSoop4kWieyoYIzhE.v
add_fileset_file z3gSJ4bseuWHvoAdylNHDW.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/z3gSJ4bseuWHvoAdylNHDW.v
add_fileset_file zF1Oe1bbeC4yb9o36NG9MH.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/zF1Oe1bbeC4yb9o36NG9MH.v
add_fileset_file zHzSp7NhI6w1mtUGqUV2GF.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/zHzSp7NhI6w1mtUGqUV2GF.v
add_fileset_file zJHvbRH33rywYdUnym8Ql.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/zJHvbRH33rywYdUnym8Ql.v
add_fileset_file zQGFxnY6BsRnebKtrggxKG.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/zQGFxnY6BsRnebKtrggxKG.v
add_fileset_file zXLvaX0ySDJUPAgB69CufG.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/zXLvaX0ySDJUPAgB69CufG.v
add_fileset_file zoR11Mxy52QrzNbPp5ptaB.v VERILOG PATH hdlsrc/WLAN11a_RX/RxPHY/zoR11Mxy52QrzNbPp5ptaB.v
add_fileset_file DIKZHcIZ3BrVaNBihUjGF.v VERILOG PATH hdlsrc/WLAN11a_RX/DIKZHcIZ3BrVaNBihUjGF.v
add_fileset_file E9Nb5vWJzKsfKhDwN3ImSD.v VERILOG PATH hdlsrc/WLAN11a_RX/E9Nb5vWJzKsfKhDwN3ImSD.v
add_fileset_file Ey6KeeQxR1b7XqdXWSWHHC.v VERILOG PATH hdlsrc/WLAN11a_RX/Ey6KeeQxR1b7XqdXWSWHHC.v
add_fileset_file J3RS7ZV1C9gmFpiG288MnH.v VERILOG PATH hdlsrc/WLAN11a_RX/J3RS7ZV1C9gmFpiG288MnH.v
add_fileset_file JwbM8m0LxEo8s8VCuCEbgG.v VERILOG PATH hdlsrc/WLAN11a_RX/JwbM8m0LxEo8s8VCuCEbgG.v
add_fileset_file KR8cQQNb1erXxCuQuZ1kLB.v VERILOG PATH hdlsrc/WLAN11a_RX/KR8cQQNb1erXxCuQuZ1kLB.v
add_fileset_file LfgZfK1fnk7JPsiMkvprqH.v VERILOG PATH hdlsrc/WLAN11a_RX/LfgZfK1fnk7JPsiMkvprqH.v
add_fileset_file RW3iv3ihfV5Tga6dzmmMtH.v VERILOG PATH hdlsrc/WLAN11a_RX/RW3iv3ihfV5Tga6dzmmMtH.v
add_fileset_file W86Z20YaSKkG0rSJVyzsqE.v VERILOG PATH hdlsrc/WLAN11a_RX/W86Z20YaSKkG0rSJVyzsqE.v
add_fileset_file WLAN11a_RX_top.v VERILOG PATH hdlsrc/WLAN11a_RX/WLAN11a_RX_top.v TOP_LEVEL_FILE
add_fileset_file WnYUQVUjZDWNu69auSuWXD.v VERILOG PATH hdlsrc/WLAN11a_RX/WnYUQVUjZDWNu69auSuWXD.v
add_fileset_file b2RXvkzydqy5vIAYvoXPQH.v VERILOG PATH hdlsrc/WLAN11a_RX/b2RXvkzydqy5vIAYvoXPQH.v
add_fileset_file c4910wQJML8uIn0WxVzVA1E.v VERILOG PATH hdlsrc/WLAN11a_RX/c4910wQJML8uIn0WxVzVA1E.v
add_fileset_file dG03oZn4Tg2PrsnIQhSGj.v VERILOG PATH hdlsrc/WLAN11a_RX/dG03oZn4Tg2PrsnIQhSGj.v
add_fileset_file dSUopG1uPnW9WpGfuJP3PC.v VERILOG PATH hdlsrc/WLAN11a_RX/dSUopG1uPnW9WpGfuJP3PC.v
add_fileset_file f2AEaGdnjWPl5Efhy29R3F.v VERILOG PATH hdlsrc/WLAN11a_RX/f2AEaGdnjWPl5Efhy29R3F.v
add_fileset_file n5JZCeOeIaz0uSffp5W6haE.v VERILOG PATH hdlsrc/WLAN11a_RX/n5JZCeOeIaz0uSffp5W6haE.v
add_fileset_file qV9WcEdQEY6JYB8IUjXaZB.v VERILOG PATH hdlsrc/WLAN11a_RX/qV9WcEdQEY6JYB8IUjXaZB.v
add_fileset_file sJW2BdSzLydyS09vMiW7T.v VERILOG PATH hdlsrc/WLAN11a_RX/sJW2BdSzLydyS09vMiW7T.v
add_fileset_file v0iYJWKXJ0CjFUq2dRmmZ.v VERILOG PATH hdlsrc/WLAN11a_RX/v0iYJWKXJ0CjFUq2dRmmZ.v
add_fileset_file vmtFmHuLVsJVtutEbKnuSC.v VERILOG PATH hdlsrc/WLAN11a_RX/vmtFmHuLVsJVtutEbKnuSC.v


# parameters
#


#
# display items
#


#
# connection point clock
#
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


#
# connection point reset
#
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


#
# connection point adc_i0_in
#
add_interface adc_i0_in conduit end
set_interface_property adc_i0_in associatedClock clock
set_interface_property adc_i0_in associatedReset ""
set_interface_property adc_i0_in ENABLED true
set_interface_property adc_i0_in EXPORT_OF ""
set_interface_property adc_i0_in PORT_NAME_MAP ""
set_interface_property adc_i0_in CMSIS_SVD_VARIABLES ""
set_interface_property adc_i0_in SVD_ADDRESS_GROUP ""

add_interface_port adc_i0_in adc_1_data_i0_in data Input 16
add_interface_port adc_i0_in adc_1_enable_i0_in enable Input 1
add_interface_port adc_i0_in adc_1_valid_i0_in valid Input 1


#
# connection point adc_q0_in
#
add_interface adc_q0_in conduit end
set_interface_property adc_q0_in associatedClock clock
set_interface_property adc_q0_in associatedReset ""
set_interface_property adc_q0_in ENABLED true
set_interface_property adc_q0_in EXPORT_OF ""
set_interface_property adc_q0_in PORT_NAME_MAP ""
set_interface_property adc_q0_in CMSIS_SVD_VARIABLES ""
set_interface_property adc_q0_in SVD_ADDRESS_GROUP ""

add_interface_port adc_q0_in adc_1_data_q0_in data Input 16
add_interface_port adc_q0_in adc_1_enable_q0_in enable Input 1
add_interface_port adc_q0_in adc_1_valid_q0_in valid Input 1


#
# connection point adc_i0_out
#
add_interface adc_i0_out conduit end
set_interface_property adc_i0_out associatedClock clock
set_interface_property adc_i0_out associatedReset ""
set_interface_property adc_i0_out ENABLED true
set_interface_property adc_i0_out EXPORT_OF ""
set_interface_property adc_i0_out PORT_NAME_MAP ""
set_interface_property adc_i0_out CMSIS_SVD_VARIABLES ""
set_interface_property adc_i0_out SVD_ADDRESS_GROUP ""

add_interface_port adc_i0_out adc_1_data_i0_out data Output 16
add_interface_port adc_i0_out adc_1_enable_i0_out enable Output 1
add_interface_port adc_i0_out adc_1_valid_i0_out valid Output 1


#
# connection point adc_q0_out
#
add_interface adc_q0_out conduit end
set_interface_property adc_q0_out associatedClock clock
set_interface_property adc_q0_out associatedReset ""
set_interface_property adc_q0_out ENABLED true
set_interface_property adc_q0_out EXPORT_OF ""
set_interface_property adc_q0_out PORT_NAME_MAP ""
set_interface_property adc_q0_out CMSIS_SVD_VARIABLES ""
set_interface_property adc_q0_out SVD_ADDRESS_GROUP ""

add_interface_port adc_q0_out adc_1_data_q0_out data Output 16
add_interface_port adc_q0_out adc_1_enable_q0_out enable Output 1
add_interface_port adc_q0_out adc_1_valid_q0_out valid Output 1


#
# connection point control
#
add_interface control conduit end
set_interface_property control associatedClock clock
set_interface_property control associatedReset ""
set_interface_property control ENABLED true
set_interface_property control EXPORT_OF ""
set_interface_property control PORT_NAME_MAP ""
set_interface_property control CMSIS_SVD_VARIABLES ""
set_interface_property control SVD_ADDRESS_GROUP ""

add_interface_port control ctrlIn control Input 32


#
# connection point status
#
add_interface status conduit end
set_interface_property status associatedClock clock
set_interface_property status associatedReset ""
set_interface_property status ENABLED true
set_interface_property status EXPORT_OF ""
set_interface_property status PORT_NAME_MAP ""
set_interface_property status CMSIS_SVD_VARIABLES ""
set_interface_property status SVD_ADDRESS_GROUP ""

add_interface_port status stsOut status_out Output 32


#
# connection point avalon_master
#
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock
set_interface_property avalon_master associatedReset reset
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master maximumPendingWriteTransactions 0
set_interface_property avalon_master readLatency 2
set_interface_property avalon_master readWaitTime 0
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master readdata readdata Input 32
add_interface_port avalon_master write write Output 1
add_interface_port avalon_master address address Output 14
add_interface_port avalon_master byteenable byteenable Output 4
add_interface_port avalon_master chipselect chipselect Output 1
add_interface_port avalon_master writedata writedata Output 32


#
# connection point monitor
#
add_interface monitor conduit end
set_interface_property monitor associatedClock clock
set_interface_property monitor associatedReset ""
set_interface_property monitor ENABLED true
set_interface_property monitor EXPORT_OF ""
set_interface_property monitor PORT_NAME_MAP ""
set_interface_property monitor CMSIS_SVD_VARIABLES ""
set_interface_property monitor SVD_ADDRESS_GROUP ""

add_interface_port monitor monitorOut monitor Output 8


#
# connection point is_sim
#
add_interface is_sim conduit end
set_interface_property is_sim associatedClock clock
set_interface_property is_sim associatedReset ""
set_interface_property is_sim ENABLED true
set_interface_property is_sim EXPORT_OF ""
set_interface_property is_sim PORT_NAME_MAP ""
set_interface_property is_sim CMSIS_SVD_VARIABLES ""
set_interface_property is_sim SVD_ADDRESS_GROUP ""

add_interface_port is_sim isSimIn is_sim_in Input 1


#
# connection point clk_enable
#
add_interface clk_enable conduit end
set_interface_property clk_enable associatedClock clock
set_interface_property clk_enable associatedReset ""
set_interface_property clk_enable ENABLED true
set_interface_property clk_enable EXPORT_OF ""
set_interface_property clk_enable PORT_NAME_MAP ""
set_interface_property clk_enable CMSIS_SVD_VARIABLES ""
set_interface_property clk_enable SVD_ADDRESS_GROUP ""

add_interface_port clk_enable clk_enable clk_enable Input 1

