# TCL File Generated by Component Editor 20.1
# Sun Nov 12 10:30:07 JST 2023
# DO NOT MODIFY


#
# WLAN11a_TX "WLAN11a_TX" v1.0
#  2023.11.12.10:30:07
#
#

#
# request TCL package from ACDS 16.1
#
package require -exact qsys 16.1


#
# module WLAN11a_TX
#
set_module_property DESCRIPTION ""
set_module_property NAME WLAN11a_TX
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME WLAN11a_TX
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


#
# file sets
#
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL WLAN11a_TX_top
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file A6bxljH07AGr8RKSblny9D.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/A6bxljH07AGr8RKSblny9D.v
add_fileset_file ABQ35mSDaI7QIBGXwvXKnB.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/ABQ35mSDaI7QIBGXwvXKnB.v
add_fileset_file AM2W0Pai3xZYfxuddMBzaH.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/AM2W0Pai3xZYfxuddMBzaH.v
add_fileset_file BwYYZxrnuGYHxEbsJwSp9G.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/BwYYZxrnuGYHxEbsJwSp9G.v
add_fileset_file DBcJ1jmonZiwF95Y07t1oC.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/DBcJ1jmonZiwF95Y07t1oC.v
add_fileset_file DWYEtLbCqAVuf0ryok2YFF.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/DWYEtLbCqAVuf0ryok2YFF.v
add_fileset_file EXkk5SVhN4i6y9DxbsYKWB.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/EXkk5SVhN4i6y9DxbsYKWB.v
add_fileset_file Efn5nhFAMMRBeSpLu4gO9.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/Efn5nhFAMMRBeSpLu4gO9.v
add_fileset_file F0CtF3MVxnzXiwQtrFlsBH.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/F0CtF3MVxnzXiwQtrFlsBH.v
add_fileset_file F5IVspHzOCWYFUIUxH8vBD.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/F5IVspHzOCWYFUIUxH8vBD.v
add_fileset_file FkhRA1wC5ut7LF1AYeDJk.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/FkhRA1wC5ut7LF1AYeDJk.v
add_fileset_file H8MSmlOmA06X2uUrWBOlt.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/H8MSmlOmA06X2uUrWBOlt.v
add_fileset_file HnLgAcdwlmzIbQyRlZ1MtE.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/HnLgAcdwlmzIbQyRlZ1MtE.v
add_fileset_file I26YX8fJDbApVYXfZGgksE.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/I26YX8fJDbApVYXfZGgksE.v
add_fileset_file IQS9jgcaf8nh4XsC7jZ8VH.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/IQS9jgcaf8nh4XsC7jZ8VH.v
add_fileset_file IXplHLr15lFEBeZZ9FOxyF.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/IXplHLr15lFEBeZZ9FOxyF.v
add_fileset_file JUzwEUg5N5sT83ltK7cWc.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/JUzwEUg5N5sT83ltK7cWc.v
add_fileset_file Lg6h7QIBhFteh0Qrci5KLD.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/Lg6h7QIBhFteh0Qrci5KLD.v
add_fileset_file LmWtAOaXODRc1t1lR4yO7E.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/LmWtAOaXODRc1t1lR4yO7E.v
add_fileset_file MRxCPzdiSVwNWoyP8eeeiF.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/MRxCPzdiSVwNWoyP8eeeiF.v
add_fileset_file MXP4bVdi2utoFmCDKgyX7B.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/MXP4bVdi2utoFmCDKgyX7B.v
add_fileset_file OJ5ZXGlOjBkArKxGSpjHjE.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/OJ5ZXGlOjBkArKxGSpjHjE.v
add_fileset_file PqhmrmhisfdZHqn5Srq3GG.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/PqhmrmhisfdZHqn5Srq3GG.v
add_fileset_file QdNLBUys3UZgmxAoZBbW8F.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/QdNLBUys3UZgmxAoZBbW8F.v
add_fileset_file QslL4dZZmobeYedPLCELLF.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/QslL4dZZmobeYedPLCELLF.v
add_fileset_file R30HhMEPBfU8v8v4r4uvVC.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/R30HhMEPBfU8v8v4r4uvVC.v
add_fileset_file T2ZSDOsb5XDcni4sIV7ybC.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/T2ZSDOsb5XDcni4sIV7ybC.v
add_fileset_file Tddht9jC69du56O1sUZb5F.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/Tddht9jC69du56O1sUZb5F.v
add_fileset_file Tlj291Pn2JD63eenhnzylE.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/Tlj291Pn2JD63eenhnzylE.v
add_fileset_file UwDbsUEqvR6xzo7siXkQb.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/UwDbsUEqvR6xzo7siXkQb.v
add_fileset_file WLAN11a_TX_TxPHY_TxPHY.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/WLAN11a_TX_TxPHY_TxPHY.v
add_fileset_file X5EVyhiZnGyDm57ArUwdsD.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/X5EVyhiZnGyDm57ArUwdsD.v
add_fileset_file XNX50X98v3CobLBFMcUIxF.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/XNX50X98v3CobLBFMcUIxF.v
add_fileset_file XlUzbVCt3wqQ4kUNqtyWMH.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/XlUzbVCt3wqQ4kUNqtyWMH.v
add_fileset_file a7lN8Uk1aEqck8gqg3k8jHG.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/a7lN8Uk1aEqck8gqg3k8jHG.v
add_fileset_file aMdw3J9jC0nWetIEF4tCoH.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/aMdw3J9jC0nWetIEF4tCoH.v
add_fileset_file baNbiRfHOBv32Af3A7PJMB.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/baNbiRfHOBv32Af3A7PJMB.v
add_fileset_file gTk4fUVqcyaUbkYlpE1iFH.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/gTk4fUVqcyaUbkYlpE1iFH.v
add_fileset_file iffwTUiSNJ15FnreXXXOFB.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/iffwTUiSNJ15FnreXXXOFB.v
add_fileset_file kG2ld4e1RGhSIP95WrM8hD.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/kG2ld4e1RGhSIP95WrM8hD.v
add_fileset_file kIHowB4UKQ296vcSn2ieZE.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/kIHowB4UKQ296vcSn2ieZE.v
add_fileset_file kU14OdbmJlRL43Cmmg8RkD.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/kU14OdbmJlRL43Cmmg8RkD.v
add_fileset_file l4PUPu0q4ejASv7i1Luj7KF.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/l4PUPu0q4ejASv7i1Luj7KF.v
add_fileset_file lIURwGgyu8sdQmEUMLYG8C.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/lIURwGgyu8sdQmEUMLYG8C.v
add_fileset_file lztxAal4UYNo5ewnupLFTB.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/lztxAal4UYNo5ewnupLFTB.v
add_fileset_file mwEaftgC72WOxHuEdajpiB.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/mwEaftgC72WOxHuEdajpiB.v
add_fileset_file n40Dd9ZBMlVqhuSRtbNPBbG.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/n40Dd9ZBMlVqhuSRtbNPBbG.v
add_fileset_file nIdOW76vTQkv7tcIit2GLG.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/nIdOW76vTQkv7tcIit2GLG.v
add_fileset_file nyZRlTz9nj8IZukyiZKh2D.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/nyZRlTz9nj8IZukyiZKh2D.v
add_fileset_file oQd73yOpQIAVARJyqtvGaC.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/oQd73yOpQIAVARJyqtvGaC.v
add_fileset_file ol9AYush6Q8gbt7U9PCSt.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/ol9AYush6Q8gbt7U9PCSt.v
add_fileset_file q3v4qawatFxSl045C273ggD.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/q3v4qawatFxSl045C273ggD.v
add_fileset_file qElj8ukbqSLD9qDjOjL4EG.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/qElj8ukbqSLD9qDjOjL4EG.v
add_fileset_file ryGtpBuXlpbq0ZZiDHz73E.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/ryGtpBuXlpbq0ZZiDHz73E.v
add_fileset_file s9RndAK19D6Qh88xHBPZvdG.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/s9RndAK19D6Qh88xHBPZvdG.v
add_fileset_file sMC48TYqImZPpkAVtLOsEH.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/sMC48TYqImZPpkAVtLOsEH.v
add_fileset_file soCLjqMUrfk2UHVcB6lO4C.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/soCLjqMUrfk2UHVcB6lO4C.v
add_fileset_file tLUNI4yffo2Q6wt4ohrqJ.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/tLUNI4yffo2Q6wt4ohrqJ.v
add_fileset_file uqvLjntlnH7bHWdeNpi7fH.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/uqvLjntlnH7bHWdeNpi7fH.v
add_fileset_file wG3uZyUPVeAVlZOwPWWNYH.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/wG3uZyUPVeAVlZOwPWWNYH.v
add_fileset_file wKKVGIR1X3HttQThZj3enC.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/wKKVGIR1X3HttQThZj3enC.v
add_fileset_file wfe8CRkUYVMB1p7YbVT3NF.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/wfe8CRkUYVMB1p7YbVT3NF.v
add_fileset_file x1ebhyKko1eOS6opwSGdXD.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/x1ebhyKko1eOS6opwSGdXD.v
add_fileset_file xMOhFy8N571f2UNhnU3erC.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/xMOhFy8N571f2UNhnU3erC.v
add_fileset_file xf0ODqqGZBD87PopNOIAH.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/xf0ODqqGZBD87PopNOIAH.v
add_fileset_file zJN0VoWQ1aGMLET0sPMyLH.v VERILOG PATH hdlsrc/WLAN11a_TX/TxPHY/zJN0VoWQ1aGMLET0sPMyLH.v
add_fileset_file EvbE35MOAkLCbd7zKkdw8C.v VERILOG PATH hdlsrc/WLAN11a_TX/EvbE35MOAkLCbd7zKkdw8C.v
add_fileset_file Hioo6f4HNMj6EcWF5ydBED.v VERILOG PATH hdlsrc/WLAN11a_TX/Hioo6f4HNMj6EcWF5ydBED.v
add_fileset_file KyoaZ8vqmm61Dfl0mMrDFD.v VERILOG PATH hdlsrc/WLAN11a_TX/KyoaZ8vqmm61Dfl0mMrDFD.v
add_fileset_file LaOeuEctEoJMTXl3xc9zEB.v VERILOG PATH hdlsrc/WLAN11a_TX/LaOeuEctEoJMTXl3xc9zEB.v
add_fileset_file LrYcCgKjnaOUcbq5anMIl.v VERILOG PATH hdlsrc/WLAN11a_TX/LrYcCgKjnaOUcbq5anMIl.v
add_fileset_file NQeTLVlz7Pa6HvUDYj7PgG.v VERILOG PATH hdlsrc/WLAN11a_TX/NQeTLVlz7Pa6HvUDYj7PgG.v
add_fileset_file OgknO1GAMvT4lGphRnzkbB.v VERILOG PATH hdlsrc/WLAN11a_TX/OgknO1GAMvT4lGphRnzkbB.v
add_fileset_file UO1IHjdIQEk3LjfS5Y8Q9.v VERILOG PATH hdlsrc/WLAN11a_TX/UO1IHjdIQEk3LjfS5Y8Q9.v
add_fileset_file UXAFZ77V31U7E7GEhcQ87B.v VERILOG PATH hdlsrc/WLAN11a_TX/UXAFZ77V31U7E7GEhcQ87B.v
add_fileset_file WLAN11a_TX_top.v VERILOG PATH hdlsrc/WLAN11a_TX/WLAN11a_TX_top.v TOP_LEVEL_FILE
add_fileset_file X1aUOPHVqirpZ6rhYnkKhF.v VERILOG PATH hdlsrc/WLAN11a_TX/X1aUOPHVqirpZ6rhYnkKhF.v
add_fileset_file c3q7KYK9nFxAYMcrZj1GrJD.v VERILOG PATH hdlsrc/WLAN11a_TX/c3q7KYK9nFxAYMcrZj1GrJD.v
add_fileset_file e0TjHHrsLnxX0OFjXMM0qUF.v VERILOG PATH hdlsrc/WLAN11a_TX/e0TjHHrsLnxX0OFjXMM0qUF.v
add_fileset_file eTqthueNnVLbtzUUV1JGOB.v VERILOG PATH hdlsrc/WLAN11a_TX/eTqthueNnVLbtzUUV1JGOB.v
add_fileset_file hjKkDrySvO6eGxDQpAVvuH.v VERILOG PATH hdlsrc/WLAN11a_TX/hjKkDrySvO6eGxDQpAVvuH.v
add_fileset_file hxSz5ApehA4hoaK3j4M05F.v VERILOG PATH hdlsrc/WLAN11a_TX/hxSz5ApehA4hoaK3j4M05F.v
add_fileset_file i6rrmf9aDzcKMIwcIFEyJDE.v VERILOG PATH hdlsrc/WLAN11a_TX/i6rrmf9aDzcKMIwcIFEyJDE.v
add_fileset_file n7uj8YQDjlLQEaIj6er7axC.v VERILOG PATH hdlsrc/WLAN11a_TX/n7uj8YQDjlLQEaIj6er7axC.v
add_fileset_file pJgBxs4LYkCJBHfkeiCaRF.v VERILOG PATH hdlsrc/WLAN11a_TX/pJgBxs4LYkCJBHfkeiCaRF.v
add_fileset_file pYoqYWZsjV21Ibhfroqf4.v VERILOG PATH hdlsrc/WLAN11a_TX/pYoqYWZsjV21Ibhfroqf4.v
add_fileset_file r0Ie83thVoSdMiyQRHy3MYC.v VERILOG PATH hdlsrc/WLAN11a_TX/r0Ie83thVoSdMiyQRHy3MYC.v
add_fileset_file vgTv3sBKeNwl7KgF6ukyo.v VERILOG PATH hdlsrc/WLAN11a_TX/vgTv3sBKeNwl7KgF6ukyo.v
add_fileset_file whCz7WwcnyKoXx1gx4ZOLD.v VERILOG PATH hdlsrc/WLAN11a_TX/whCz7WwcnyKoXx1gx4ZOLD.v
add_fileset_file x9gjlqCsULY8ZRk2aFpR2mH.v VERILOG PATH hdlsrc/WLAN11a_TX/x9gjlqCsULY8ZRk2aFpR2mH.v
add_fileset_file y5cqjGpX1R3rbtrJackT7C.v VERILOG PATH hdlsrc/WLAN11a_TX/y5cqjGpX1R3rbtrJackT7C.v
add_fileset_file y7T1bbxXzGYm1u6qtN0fzD.v VERILOG PATH hdlsrc/WLAN11a_TX/y7T1bbxXzGYm1u6qtN0fzD.v


#
# parameters
#


#
# display items
#


#
# connection point clock
#
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


#
# connection point reset
#
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


#
# connection point dac_i0_in
#
add_interface dac_i0_in conduit end
set_interface_property dac_i0_in associatedClock clock
set_interface_property dac_i0_in associatedReset ""
set_interface_property dac_i0_in ENABLED true
set_interface_property dac_i0_in EXPORT_OF ""
set_interface_property dac_i0_in PORT_NAME_MAP ""
set_interface_property dac_i0_in CMSIS_SVD_VARIABLES ""
set_interface_property dac_i0_in SVD_ADDRESS_GROUP ""

add_interface_port dac_i0_in dac_1_data_i0_in data Input 16
add_interface_port dac_i0_in dac_1_enable_i0_out enable Output 1
add_interface_port dac_i0_in dac_1_valid_i0_out valid Output 1


#
# connection point dac_q0_in
#
add_interface dac_q0_in conduit end
set_interface_property dac_q0_in associatedClock clock
set_interface_property dac_q0_in associatedReset ""
set_interface_property dac_q0_in ENABLED true
set_interface_property dac_q0_in EXPORT_OF ""
set_interface_property dac_q0_in PORT_NAME_MAP ""
set_interface_property dac_q0_in CMSIS_SVD_VARIABLES ""
set_interface_property dac_q0_in SVD_ADDRESS_GROUP ""

add_interface_port dac_q0_in dac_1_data_q0_in data Input 16
add_interface_port dac_q0_in dac_1_enable_q0_out enable Output 1
add_interface_port dac_q0_in dac_1_valid_q0_out valid Output 1


#
# connection point dac_i0_out
#
add_interface dac_i0_out conduit end
set_interface_property dac_i0_out associatedClock clock
set_interface_property dac_i0_out associatedReset ""
set_interface_property dac_i0_out ENABLED true
set_interface_property dac_i0_out EXPORT_OF ""
set_interface_property dac_i0_out PORT_NAME_MAP ""
set_interface_property dac_i0_out CMSIS_SVD_VARIABLES ""
set_interface_property dac_i0_out SVD_ADDRESS_GROUP ""

add_interface_port dac_i0_out dac_1_data_i0_out data Output 16
add_interface_port dac_i0_out dac_1_enable_i0_in enable Input 1
add_interface_port dac_i0_out dac_1_valid_i0_in valid Input 1


#
# connection point dac_q0_out
#
add_interface dac_q0_out conduit end
set_interface_property dac_q0_out associatedClock clock
set_interface_property dac_q0_out associatedReset ""
set_interface_property dac_q0_out ENABLED true
set_interface_property dac_q0_out EXPORT_OF ""
set_interface_property dac_q0_out PORT_NAME_MAP ""
set_interface_property dac_q0_out CMSIS_SVD_VARIABLES ""
set_interface_property dac_q0_out SVD_ADDRESS_GROUP ""

add_interface_port dac_q0_out dac_1_data_q0_out data Output 16
add_interface_port dac_q0_out dac_1_enable_q0_in enable Input 1
add_interface_port dac_q0_out dac_1_valid_q0_in valid Input 1


#
# connection point control
#
add_interface control conduit end
set_interface_property control associatedClock clock
set_interface_property control associatedReset ""
set_interface_property control ENABLED true
set_interface_property control EXPORT_OF ""
set_interface_property control PORT_NAME_MAP ""
set_interface_property control CMSIS_SVD_VARIABLES ""
set_interface_property control SVD_ADDRESS_GROUP ""

add_interface_port control ctrlIn control_in Input 32


#
# connection point status
#
add_interface status conduit end
set_interface_property status associatedClock clock
set_interface_property status associatedReset ""
set_interface_property status ENABLED true
set_interface_property status EXPORT_OF ""
set_interface_property status PORT_NAME_MAP ""
set_interface_property status CMSIS_SVD_VARIABLES ""
set_interface_property status SVD_ADDRESS_GROUP ""

add_interface_port status stsOut status_out Output 32


#
# connection point avalon_master
#
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock
set_interface_property avalon_master associatedReset reset
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master maximumPendingWriteTransactions 0
set_interface_property avalon_master readLatency 2
set_interface_property avalon_master readWaitTime 0
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master readdata readdata Input 32
add_interface_port avalon_master address address Output 14
add_interface_port avalon_master byteenable byteenable Output 4
add_interface_port avalon_master chipselect chipselect Output 1
add_interface_port avalon_master write write Output 1
add_interface_port avalon_master writedata writedata Output 32


#
# connection point monitor
#
add_interface monitor conduit end
set_interface_property monitor associatedClock clock
set_interface_property monitor associatedReset ""
set_interface_property monitor ENABLED true
set_interface_property monitor EXPORT_OF ""
set_interface_property monitor PORT_NAME_MAP ""
set_interface_property monitor CMSIS_SVD_VARIABLES ""
set_interface_property monitor SVD_ADDRESS_GROUP ""

add_interface_port monitor monitorOut monitor Output 8


#
# connection point clk_enable
#
add_interface clk_enable conduit end
set_interface_property clk_enable associatedClock clock
set_interface_property clk_enable associatedReset ""
set_interface_property clk_enable ENABLED true
set_interface_property clk_enable EXPORT_OF ""
set_interface_property clk_enable PORT_NAME_MAP ""
set_interface_property clk_enable CMSIS_SVD_VARIABLES ""
set_interface_property clk_enable SVD_ADDRESS_GROUP ""

add_interface_port clk_enable clk_enable clk_enable Input 1

